language: go
go:
  - 1.5
  - 1.6
  - tip

sudo: false

before_script:
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install --update
script:
  - gometalinter --deadline=30s .
  - go test -v
